get_filename_component(ANDROID_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)

set(ANDROID_JNI_INC
		${ANDROID_CMAKE_DIR}/jni
		)

set(ANDROID_JNI_SRC
		${ANDROID_CMAKE_DIR}/jni/txg_jni_util.cpp
		)

set(ANDROID_UTILS_INC
		${ANDROID_CMAKE_DIR}/utils
		)

set(ANDROID_UTILS_SRC
		${ANDROID_CMAKE_DIR}/utils/callstack.cpp
		)

set(ANDROID_INC
		${ANDROID_JNI_INC}
		${ANDROID_UTILS_INC}
		)

set(ANDROID_SRC
		${ANDROID_JNI_SRC}
		${ANDROID_UTILS_SRC}
		)